### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vanlong441** [shutterstock/public-api-javascript-sdk#12]
`> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 107 errors                                                                                                                                    12:58:24 PM
These dependencies were not found:

* ApiClient in ./node_modules/shutterstock-api/src/index.js
* api/AudioApi in ./node_modules/shutterstock-api/src/index.js
* api/ComputerVisionApi in ./node_modules/shutterstock-api/src/index.js   
* api/ContributorsApi in ./node_modules/shutterstock-api/src/index.js     
* api/EditorialApi in ./node_modules/shutterstock-api/src/index.js        
* api/ImagesApi in ./node_modules/shutterstock-api/src/index.js
* api/TestApi in ./node_modules/shutterstock-api/src/index.js
* api/UsersApi in ./node_modules/shutterstock-api/src/index.js
* api/VideosApi in ./node_modules/shutterstock-api/src/index.js
* model/AccessTokenDetails in ./node_modules/shutterstock-api/src/index.js
* model/Album in ./node_modules/shutterstock-api/src/index.js
* model/Allotment in ./node_modules/shutterstock-api/src/index.js
* model/Artist in ./node_modules/shutterstock-api/src/index.js
* model/Audio in ./node_modules/shutterstock-api/src/index.js
* model/AudioAssetDetails in ./node_modules/shutterstock-api/src/index.js 
* model/AudioAssets in ./node_modules/shutterstock-api/src/index.js       
* model/AudioDataList in ./node_modules/shutterstock-api/src/index.js     
* model/AudioSearchResults in ./node_modules/shutterstock-api/src/index.js
* model/Category in ./node_modules/shutterstock-api/src/index.js
* model/CategoryDataList in ./node_modules/shutterstock-api/src/index.js
* model/Collection in ./node_modules/shutterstock-api/src/index.js
* model/CollectionCreateRequest in ./node_modules/shutterstock-api/src/index.js
* model/CollectionCreateResponse in ./node_modules/shutterstock-api/src/index.js
* model/CollectionDataList in ./node_modules/shutterstock-api/src/index.js
* model/CollectionItem in ./node_modules/shutterstock-api/src/index.js
* model/CollectionItemDataList in ./node_modules/shutterstock-api/src/index.js
* model/CollectionItemRequest in ./node_modules/shutterstock-api/src/index.js
* model/CollectionUpdateRequest in ./node_modules/shutterstock-api/src/index.js
* model/Contributor in ./node_modules/shutterstock-api/src/index.js
* model/ContributorProfile in ./node_modules/shutterstock-api/src/index.js
* model/ContributorProfileDataList in ./node_modules/shutterstock-api/src/index.js
* model/ContributorProfileSocialMedia in ./node_modules/shutterstock-api/src/index.js
* model/Cookie in ./node_modules/shutterstock-api/src/index.js
* model/DownloadHistory in ./node_modules/shutterstock-api/src/index.js
* model/DownloadHistoryDataList in ./node_modules/shutterstock-api/src/index.js
* model/DownloadHistoryFormatDetails in ./node_modules/shutterstock-api/src/index.js
* model/DownloadHistoryMediaDetails in ./node_modules/shutterstock-api/src/index.js
* model/DownloadHistoryUserDetails in ./node_modules/shutterstock-api/src/index.js
* model/EditorialAssets in ./node_modules/shutterstock-api/src/index.js
* model/EditorialCategory in ./node_modules/shutterstock-api/src/index.js
* model/EditorialContent in ./node_modules/shutterstock-api/src/index.js
* model/EditorialContentDataList in ./node_modules/shutterstock-api/src/index.js
* model/EditorialCoverItem in ./node_modules/shutterstock-api/src/index.js
* model/EditorialLivefeed in ./node_modules/shutterstock-api/src/index.js
* model/EditorialLivefeedList in ./node_modules/shutterstock-api/src/index.js
* model/EditorialSearchResults in ./node_modules/shutterstock-api/src/index.js
* model/Error in ./node_modules/shutterstock-api/src/index.js
* model/FeaturedCollection in ./node_modules/shutterstock-api/src/index.js
* model/FeaturedCollectionCoverItem in ./node_modules/shutterstock-api/src/index.js
* model/FeaturedCollectionDataList in ./node_modules/shutterstock-api/src/index.js
* model/GenreList in ./node_modules/shutterstock-api/src/index.js
* model/Image in ./node_modules/shutterstock-api/src/index.js
* model/ImageAssets in ./node_modules/shutterstock-api/src/index.js
* model/ImageCreateRequest in ./node_modules/shutterstock-api/src/index.js
* model/ImageCreateResponse in ./node_modules/shutterstock-api/src/index.js
* model/ImageDataList in ./node_modules/shutterstock-api/src/index.js
* model/ImageSearchResults in ./node_modules/shutterstock-api/src/index.js
* model/ImageSizeDetails in ./node_modules/shutterstock-api/src/index.js
* model/InlineResponse201 in ./node_modules/shutterstock-api/src/index.js
* model/InstrumentList in ./node_modules/shutterstock-api/src/index.js
* model/Language in ./node_modules/shutterstock-api/src/index.js
* model/LicenseAudio in ./node_modules/shutterstock-api/src/index.js
* model/LicenseAudioRequest in ./node_modules/shutterstock-api/src/index.js
* model/LicenseAudioResult in ./node_modules/shutterstock-api/src/index.js
* model/LicenseAudioResultDataList in ./node_modules/shutterstock-api/src/index.js
* model/LicenseEditorialContent in ./node_modules/shutterstock-api/src/index.js
* model/LicenseEditorialContentRequest in ./node_modules/shutterstock-api/src/index.js
* model/LicenseEditorialContentResult in ./node_modules/shutterstock-api/src/index.js
* model/LicenseEditorialContentResultDataList in ./node_modules/shutterstock-api/src/index.js
* model/LicenseFormat in ./node_modules/shutterstock-api/src/index.js
* model/LicenseImage in ./node_modules/shutterstock-api/src/index.js
* model/LicenseImageRequest in ./node_modules/shutterstock-api/src/index.js
* model/LicenseImageResult in ./node_modules/shutterstock-api/src/index.js
* model/LicenseImageResultDataList in ./node_modules/shutterstock-api/src/index.js
* model/LicenseRequestMetadata in ./node_modules/shutterstock-api/src/index.js
* model/LicenseVideo in ./node_modules/shutterstock-api/src/index.js
* model/LicenseVideoRequest in ./node_modules/shutterstock-api/src/index.js
* model/LicenseVideoResult in ./node_modules/shutterstock-api/src/index.js
* model/LicenseVideoResultDataList in ./node_modules/shutterstock-api/src/index.js
* model/Model in ./node_modules/shutterstock-api/src/index.js
* model/ModelRelease in ./node_modules/shutterstock-api/src/index.js
* model/MoodList in ./node_modules/shutterstock-api/src/index.js
* model/Price in ./node_modules/shutterstock-api/src/index.js
* model/Recommendation in ./node_modules/shutterstock-api/src/index.js
* model/RecommendationDataList in ./node_modules/shutterstock-api/src/index.js
* model/RedownloadImage in ./node_modules/shutterstock-api/src/index.js
* model/RedownloadVideo in ./node_modules/shutterstock-api/src/index.js
* model/Subscription in ./node_modules/shutterstock-api/src/index.js
* model/SubscriptionDataList in ./node_modules/shutterstock-api/src/index.js
* model/SubscriptionMetadata in ./node_modules/shutterstock-api/src/index.js
* model/TestEcho in ./node_modules/shutterstock-api/src/index.js
* model/TestValidate in ./node_modules/shutterstock-api/src/index.js
* model/TestValidateHeader in ./node_modules/shutterstock-api/src/index.js
* model/TestValidateQuery in ./node_modules/shutterstock-api/src/index.js
* model/Thumbnail in ./node_modules/shutterstock-api/src/index.js
* model/UpdatedMedia in ./node_modules/shutterstock-api/src/index.js
* model/UpdatedMediaDataList in ./node_modules/shutterstock-api/src/index.js
* model/Url in ./node_modules/shutterstock-api/src/index.js
* model/Urls in ./node_modules/shutterstock-api/src/index.js
* model/UserDetails in ./node_modules/shutterstock-api/src/index.js
* model/UserPostRequest in ./node_modules/shutterstock-api/src/index.js
* model/UserPostResponse in ./node_modules/shutterstock-api/src/index.js
* model/Video in ./node_modules/shutterstock-api/src/index.js
* model/VideoAssets in ./node_modules/shutterstock-api/src/index.js
* model/VideoDataList in ./node_modules/shutterstock-api/src/index.js
* model/VideoSearchResults in ./node_modules/shutterstock-api/src/index.js
* model/VideoSizeDetails in ./node_modules/shutterstock-api/src/index.js

To install them, you can run: npm install --save ApiClient api/AudioApi api/ComputerVisionApi api/ContributorsApi api/EditorialApi api/ImagesApi api/TestApi api/UsersApi api/VideosApi 
model/AccessTokenDetails model/Album model/Allotment model/Artist model/Audio model/AudioAssetDetails model/AudioAssets model/AudioDataList model/AudioSearchResults model/Category model/CategoryDataList model/Collection model/CollectionCreateRequest model/CollectionCreateResponse model/CollectionDataList model/CollectionItem model/CollectionItemDataList model/CollectionItemRequest model/CollectionUpdateRequest model/Contributor model/ContributorProfile model/ContributorProfileDataList model/ContributorProfileSocialMedia model/Cookie model/DownloadHistory model/DownloadHistoryDataList model/DownloadHistoryFormatDetails model/DownloadHistoryMediaDetails model/DownloadHistoryUserDetails model/EditorialAssets model/EditorialCategory model/EditorialContent model/EditorialContentDataList model/EditorialCoverItem model/EditorialLivefeed model/EditorialLivefeedList model/EditorialSearchResults model/Error model/FeaturedCollection model/FeaturedCollectionCoverItem model/FeaturedCollectionDataList model/GenreList model/Image model/ImageAssets model/ImageCreateRequest model/ImageCreateResponse model/ImageDataList model/ImageSearchResults model/ImageSizeDetails model/InlineResponse201 model/InstrumentList model/Language model/LicenseAudio model/LicenseAudioRequest model/LicenseAudioResult model/LicenseAudioResultDataList model/LicenseEditorialContent model/LicenseEditorialContentRequest model/LicenseEditorialContentResult model/LicenseEditorialContentResultDataList model/LicenseFormat model/LicenseImage model/LicenseImageRequest model/LicenseImageResult model/LicenseImageResultDataList model/LicenseRequestMetadata model/LicenseVideo model/LicenseVideoRequest model/LicenseVideoResult model/LicenseVideoResultDataList model/Model model/ModelRelease model/MoodList model/Price model/Recommendation model/RecommendationDataList model/RedownloadImage model/RedownloadVideo model/Subscription model/SubscriptionDataList model/SubscriptionMetadata model/TestEcho model/TestValidate model/TestValidateHeader model/TestValidateQuery model/Thumbnail model/UpdatedMedia model/UpdatedMediaDataList model/Url model/Urls model/UserDetails model/UserPostRequest model/UserPostResponse model/Video model/VideoAssets model/VideoDataList model/VideoSearchResults model/VideoSizeDetails
Terminate batch job (Y/N)? ^C`

**Comment by andrevvm** [comment]
Getting the same error on a Vue project

**Comment by msmol** [comment]
Fixed in v1.0.18: https://www.npmjs.com/package/shutterstock-api/v/1.0.18

Thanks for reporting the issue @vanlong441 @andrevvm
