### ISSUE TITLE
UsersApi has typo in methods' names (Package version "^1.0.37")

### ISSUE THREAD

**Issue by dehcastro** [shutterstock/public-api-javascript-sdk#22]
When creating a new UsersApi instance, it's returned with typos in the following methods:

 - getUserSubsciptionListWithHttpInfo() **<-- it's missing a "r" in "subscription"**
- getUserSubsciptionList() **<-- it's missing a "r" in "subscription"**

Check it down below:

```
exports {
  apiClient: exports {
    basePath: 'https://api.shutterstock.com',
    authentications: { basic: [Object], customer_accessCode: [Object] },
    defaultHeaders: { 'User-Agent': 'public-api-sdk-generator/{{projectVersion}}' },
    timeout: 60000,
    cache: true,
    enableCookies: false,
    agent: Agent { _defaults: [], jar: [CookieJar] },
    requestAgent: null
  },
  getAccessTokenWithHttpInfo: [Function (anonymous)],
  getAccessToken: [Function (anonymous)],
  getUserWithHttpInfo: [Function (anonymous)],
  getUser: [Function (anonymous)],
  getUserSubsciptionListWithHttpInfo: [Function (anonymous)], // <-- Typo Here
  getUserSubsciptionList: [Function (anonymous)] // <-- Typo Here
}
```
Package version:

```
"dependencies": {
  "shutterstock-api": "^1.0.37"
}
```

**Comment by dehcastro** [comment]
I'm closing this issue because I've opened it in the wrong repository! :(

**Comment by dehcastro** [comment]
Oh WOW ... I'm reopening it because it turns out to BE the correct repository! I'm so sorry! 😳

**Comment by ayeshakr** [comment]
Hi @dehcastro ! This has been fixed in v.1.1.0, you can see the updated names here https://github.com/shutterstock/public-api-javascript-sdk/blob/master/src/api/UsersApi.js#L141
